name: GitHub Actions Demo

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:         # Allows manual run from GitHub UI

jobs:
  ping-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render backend
        run: curl https://realestate-fk4g.onrender.com

